### ISSUE TITLE
Double Check - OLED 

### ISSUE THREAD

**Issue by EstevesDouglas** [lhc/nodeLHC-ESP32#14]
Contribua com revisões no esquemático e footprint do projeto.

Checklist nodeLHC review - double check - OLED

**Comment by pedrominatel** [comment]
Quais são os modelos mais utilizados de OLED?

https://www.filipeflop.com/produto/display-oled-0-96-polegadas-i2c-azul/
https://www.filipeflop.com/produto/display-oled-0-96-i2c-azul-amarelo/

**Comment by EstevesDouglas** [comment]
Pelo que eu andei pesquisando aqui é esse Azul o mais usado.

Mas o legal que eles seguem o mesmo padrão.

**Comment by EstevesDouglas** [comment]
via Daniel Vieira
Eu fiz a revisão do esquemático da pcb do ESP 32 o jumper do display oled ficou bom, pois tem displays que o pino gnd e vc estão invertidos conforme as figuras.
